Imports DevExpress.XtraEditors
Imports DevExpress.XtraGrid
Imports DevExpress.XtraGrid.Views.Grid
Imports DevExpress.XtraPivotGrid
Imports System
Imports System.Collections.Generic
Imports System.Drawing
Imports System.Windows.Forms

Namespace DrillDownDataSourceExample
	Partial Public Class Form1
		Inherits DevExpress.XtraEditors.XtraForm

		Private serverMode As Boolean = False
		Public Sub New()
			InitializeComponent()
			AddHandler pivotGridControl1.CellDoubleClick, AddressOf PivotGridControl1_CellDoubleClick
			' This line of code is generated by Data Source Configuration Wizard
			linqServerModeSource1.QueryableSource = (New DrillDownDataSourceExample.DataClasses1DataContext()).Invoices
		End Sub

		Private Sub PivotGridControl1_CellDoubleClick(ByVal sender As Object, ByVal e As DevExpress.XtraPivotGrid.PivotCellEventArgs)
			Dim drillDownDataSource As PivotDrillDownDataSource
			If serverMode Then
			   drillDownDataSource = e.CreateDrillDownDataSource(25, New List(Of String) From {"ShipName"})
			Else
				drillDownDataSource = e.CreateDrillDownDataSource(25)
			End If
			Dim dataform As Form = CreateDrillDownForm(drillDownDataSource)
			dataform.ShowDialog()
			dataform.Dispose()
		End Sub

		Private Sub Form1_Load(ByVal sender As Object, ByVal e As EventArgs) Handles Me.Load
			' TODO: This line of code loads data into the 'nWDataSet.Invoices' table. You can move, or remove it, as needed.
			Me.invoicesTableAdapter.Fill(Me.nWDataSet.Invoices)
			SetPivotGridDataSource()
		End Sub

		Private Function CreateDrillDownForm(ByVal dataSource As PivotDrillDownDataSource) As Form
			Dim form As New Form()
			form.Text = "Underlying Data"
			Dim grid As New GridControl()
			grid.Parent = form
			grid.Dock = DockStyle.Fill
			grid.DataSource = dataSource
			form.Bounds = New Rectangle(100, 100, 800, 400)
			grid.DataSource = form.Bounds
			Dim gridView1 As New GridView()
			grid.MainView = gridView1
			gridView1.Columns("OrderDate").DisplayFormat.FormatType = DevExpress.Utils.FormatType.DateTime
			form.Text = String.Format("Underlying Data - {0} Records", dataSource.RowCount)
			Return form
		End Function

		Private Sub toggleSwitch1_Toggled(ByVal sender As Object, ByVal e As EventArgs) Handles toggleSwitch1.Toggled
			serverMode = DirectCast(sender, ToggleSwitch).IsOn
			SetPivotGridDataSource()
		End Sub

		Private Sub SetPivotGridDataSource()
			If serverMode Then
				pivotGridControl1.DataSource = linqServerModeSource1
			Else
				pivotGridControl1.DataSource = invoicesBindingSource
			End If
		End Sub

		Private Sub btnGrandTotal_Click(ByVal sender As Object, ByVal e As EventArgs) Handles btnGrandTotal.Click
			Dim drillDownDataSource As PivotDrillDownDataSource = pivotGridControl1.CreateDrillDownDataSource()
			Dim dataform As Form = CreateDrillDownForm(drillDownDataSource)
			dataform.ShowDialog()
			dataform.Dispose()
		End Sub
	End Class
End Namespace
